name: MJBarChart Publish

on:
    release:
        types: [released]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write  # Required for OIDC
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Node and NPM
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"
            - name: Install and Build
              run: npm ci && npm run build
            - name: Publish to NPM
              run: npm publish --access public
